import { Container } from '@/components/ui/container';
import { cn } from '@/lib/cn';
import type { Metadata } from 'next';
import { Inconsolata, Inter, Lora } from 'next/font/google';
import './globals.css';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });
const lora = Lora({ subsets: ['latin'], variable: '--font-serif' });
const inconsolata = Inconsolata({
	subsets: ['latin'],
	variable: '--font-mono',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const theme = cookies().get('theme')?.value;

	return (
		<html lang='en'>
			<body
				className={cn(
					inter.variable,
					lora.variable,
					inconsolata.variable,
					theme
				)}
			>
				<Container as='main' className='py-[3.625rem]'>
					{children}
				</Container>
			</body>
		</html>
	);
}
