import { MainLayout } from '@/components/layout/main-layout';
import { cn } from '@/lib/cn';
import { getConfig } from '@/utils/get-config';
import type { Metadata } from 'next';
import { Inconsolata, Inter, Lora } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });
const lora = Lora({ subsets: ['latin'], variable: '--font-serif' });
const inconsolata = Inconsolata({
	subsets: ['latin'],
	variable: '--font-mono',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const { font, theme } = getConfig();

	return (
		<html lang='en'>
			<body
				className={cn(
					inter.variable,
					lora.variable,
					inconsolata.variable,
					theme,
					font
				)}
			>
				<MainLayout>{children}</MainLayout>
			</body>
		</html>
	);
}
